// PEOPLE ---------------------------------
var celebFemaleList = [
  "Dianne Abbot",
  "Michelle Obama",
  "Amber Rudd",
  "Emily Thornburry",
  "Adele",
  "Ariana Grande",
  "Angelina Jolie",
  "Barbara Streisand",
  "Beyonce",
  "Britney Spears",
  "Cameron Diaz",
  "Carrie Fisher",
  "Cher",
  "Catherine Zeta-Jones",
  "Celine Dion",
  "Courteney Cox",
  "Dakota Fanning",
  "Demi Moore",
  "Dolly Parton",
  "Drew Barrymore",
  "Ellen DeGeneres",
  "Ellen Page",
  "Emilia Clarke",
  "Emma Watson",
  "Eva Mendes",
  "Grace Kelly",
  "Gwyneth Paltrow",
  "Halle Berry",
  "Helen Mirren",
  "Helena Bonham Carter",
  "Hilary Duff",
  "Hilary Swank",
  "J.K Rowling",
  "Jennifer Aniston",
  "Jennifer Hudson",
  "Jennifer Lawrence",
  "Jennifer Lopez",
  "Jessica Alba",
  "Judi Dench",
  "Julia Roberts",
  "Kate Beckinsale",
  "Kate Hudson",
  "Kate Winslet",
  "Katy Perry",
  "Keira Knightley",
  "Kim Basinger",
  "Kim Kardashian",
  "Lindsay Lohan",
  "Lisa Kudrow",
  "Meg Ryan",
  "Megan Fox",
  "Meryl Streep",
  "Mila Kunis",
  "Miley Cyrus",
  "Khloé Kardashian",
  "Macy Gray",
  "Demi Lovato",
  "Pixie Lott",
  "Kate Moss",
  "Cara Delevingne",
  "Kendall Jenner",
  "Oprah Winfrey",
  "Theresa May",
  "Natalie Portman",
  "Nia Long",
  "Nicole Kidman",
  "Penelope Cruz",
  "Queen Latifah",
  "Reese Witherspoon",
  "Renee Zellweger",
  "Rihanna",
  "Sandra Bullock",
  "Scarlett Johansson",
  "Selena Gomez",
  "Taylor Swift",
  "Whoopi Goldberg",
]
var femaleList = [
  "Woman",
  "[LOC] Woman",
  "Drunk Woman",
  "Drunk [LOC] Woman",
  "Drunk [LOC] [OCC]",
  "[LOC] [OCC]", ,
  "[OCC]",
]
var celebMaleList = [
  "Mike Pence",
  "Jeremy Corbyn",
  "Boris Johnson",
  "Jacob Rees-Mogg",
  "James O' Brien",
  "Gordon Brown",
  "David Cameron",
  "Barrack Obama",
  "Ken Clarke",
  "Sajid Javid",
  "John Bercow",
  "Nigel Farage",
  "Ed Milliband",
  "David Davis",
  "Adam Sandler",
  "Al Pacino",
  "Anthony Hopkins",
  "Arnold Schwarzenegger",
  "Ashton Kutcher",
  "Ben Affleck",
  "Ben Stiller",
  "Benedict Cumberbatch",
  "Bill Murray",
  "Bill O'Reilly",
  "Bill Paxton",
  "Billy Joel",
  "Bon Jovi",
  "Brad Pitt",
  "Brian Cox",
  "Elon Musk",
  "Joe Rogan",
  "Ozzy Osbourne",
  "Bruce Lee",
  "Bruce Springsteen",
  "Bruce Willis",
  "Bruno Mars",
  "Calvin Harris",
  "Chance The Rapper",
  "Channing Tatum",
  "Charlie Sheen",
  "Chris Evans",
  "Chris Hemsworth",
  "Chris Martin",
  "Chris Rock",
  "Chris Tucker",
  "Christian Bale",
  "Christopher Reeve",
  "Christopher Walken",
  "Chuck Norris",
  "Clint Eastwood",
  "Colin Farrell",
  "Colin Firth",
  "Conor McGregor",
  "Cristiano Ronaldo",
  "Daniel Craig",
  "Daniel Radcliffe",
  "Danny DeVito",
  "Danny Glover",
  "Dave Chappelle",
  "Dennis Hopper",
  "Denzel Washington",
  "Dick Van Dyke",
  "Dr. Dre",
  "Dr. Phil",
  "Drake",
  "Dustin Hoffman",
  "Dwayne Johnson",
  "Ed Sheeran",
  "Eddie Murphy",
  "Elton John",
  "Fernando Alonso",
  "Forest Whitaker",
  "Gareth Bale",
  "Gene Wilder",
  "George Clooney",
  "Gordon Ramsay",
  "Guy Pearce",
  "Harrison Ford",
  "Heath Ledger",
  "Howard Stern",
  "Hugh Grant",
  "Hugh Jackman",
  "Hugh Laurie",
  "Ian McKellen",
  "Ice Cube",
  "Idris Elba",
  "Jack Nicholson",
  "Jackie Chan",
  "Jake Gyllenhaal",
  "James Franco",
  "James Woods",
  "Jamie Foxx",
  "Jared Leto",
  "Jason Statham",
  "Jay Z",
  "Jet Li",
  "Jim Carrey",
  "Joaquin Phoenix",
  "Joe Pesci",
  "John Travolta",
  "Johnny Depp",
  "Johnny Knoxville",
  "Jude Law",
  "Justin Bieber",
  "Justin Timberlake",
  "Keanu Reeves",
  "Kevin Bacon",
  "Kevin Costner",
  "Kevin Hart",
  "Kevin Spacey",
  "Laurence Fishbourne",
  "LeBron James",
  "Leonardo DiCaprio",
  "Lewis Hamilton",
  "Liam Neeson",
  "Lionel Messi",
  "Louis C.K.",
  "Ludacris",
  "Macaulay Culkin",
  "Mark Hamill",
  "Mark Wahlberg",
  "Marlon Brando",
  "Marlon Wayans",
  "Matthew McConaughey",
  "Mel Gibson",
  "Michael J. Fox",
  "Mike Myers",
  "Morgan Freeman",
  "Neymar",
  "Nick Frost",
  "Novak Djokovic",
  "Orlando Bloom",
  "Patrick Swayze",
  "Pierce Brosnan",
  "Rob Schneider",
  "Robert De Niro",
  "Robert Downey Jr.",
  "Russell Brand",
  "Russell Crowe",
  "Ryan Gosling",
  "Ryan Reynolds",
  "Sacha Baron Cohen",
  "Samuel L. Jackson",
  "Sean Bean",
  "Sean Connery",
  "Sean Diddy Combs",
  "Sebastian Vettel",
  "Seth Green",
  "Seth MacFarlane",
  "Shia LaBeouf",
  "Simon Cowell",
  "Simon Pegg",
  "Stephen Curry",
  "Steve Buscemi",
  "Sylvester Stallone",
  "Tiger Woods",
  "Tom Cruise",
  "Tom Hanks",
  "Usain Bolt",
  "Vin Diesel",
  "Will Ferrell",
  "Donald Trump",
  "Will Smith",
  "Zac Efron",
  "R. Kelly",
  "Tito Ortiz",
  "Jimmy Kimmel",
  "Jay Leno",
  "J. Cole",
  "Sam Smith",
  "Soulja Boy",
  "Terry Crews",
];
var maleList = [
  "Man",
  "[LOC] Man",
  "Drunk Man",
  "Drunk [LOC] Man",
  "Drunk [OCC]",
  "[LOC] [OCC]",
  "[OCC]",
]
var genderChoice = [
  "Male",
  "Female",
]
var occupationList = [
  "Academic",
  "High School Student",
  "University Student",
  "Protestor",
  "Activist",
  "Accountant",
  "Actor",
  "Acupuncturist",
  "Pilot",
  "Air Traffic Controller",
  "Ambulance Driver",
  "Paramdemic",
  "Anaesthetist",
  "Archaeologist",
  "Architect",
  "Army Officer",
  "Art Teacher",
  "Auctioneer",
  "Author",
  "Baker",
  "Bank Worker",
  "Bartender",
  "Barista",
  "Barrister",
  "Beauty Therapist",
  "Beef Farmer",
  "Tattooist",
  "Bookmaker",
  "Botanist",
  "Brewer",
  "Bricklayer",
  "Bus Driver",
  "Butcher",
  "Restaurant Manager",
  "Car Park Attendant",
  "Cardiologist",
  "Carpenter",
  "Chef",
  "Chemist",
  "Chiropractor",
  "Cinema Manager",
  "Civil Servant",
  "Concierge",
  "Crane Operator",
  "Customer Officer",
  "Dancer",
  "Delivery Driver",
  "Dentist",
  "Diver",
  "Driving Instructor",
  "Drug and Alcohol Counsellor",
  "Economist",
  "Electrician",
  "Entrepreneur",
  "Farmer",
  "Fashion Designer",
  "Fast Food Worker",
  "Investment Banker",
  "Firefighter",
  "Fisherman",
  "Fitness Instructor",
  "Flight Attendant",
  "Florist",
  "Flying instructor",
  "Forklift Driver",
  "Funeral Director",
  "Museum Curator",
  "Museum Guide",
  "Game Developer",
  "General Practitioner",
  "Geologist",
  "Geophysicist",
  "Goldsmith",
  "Graphic Designer",
  "Gunsmith",
  "Gynaecologist",
  "Hairdresser",
  "Helicopter Pilot",
  "Historian",
  "Horse Trainer",
  "Hospital Pharmacist",
  "Hotel Manager",
  "Immigration Officer",
  "IT Admin",
  "Insurance Broker",
  "Judge",
  "Lab Worker",
  "Librarian",
  "Locksmith",
  "Interpreter",
  "Massage Therapist",
  "Meteorologist",
  "Midwife",
  "Miner",
  "Music Teacher",
  "Nanny",
  "Navy Sailor",
  "Navy Technician",
  "Neurosurgeon",
  "Nurse",
  "Nutritionist",
  "Office Manager",
  "Paediatrician",
  "Ticket Inspector",
  "Pest Controller",
  "Pharmacist",
  "Pharmacologist",
  "Photographer",
  "Gym Teacher",
  "Physicist",
  "Physiotherapist",
  "Plastic Surgeon",
  "Plumber",
  "Police Officer",
  "Primary School Teacher",
  "Prison Officer",
  "Private Investigator",
  "Property Developer",
  "Property Manager",
  "Publisher",
  "Radio Presenter",
  "Garbage Collector",
  "Retail Worker",
  "Road Worker",
  "Roof Tiler",
  "Safety Inspector",
  "Food Safety Inspector",
  "Scaffolder",
  "School Principal",
  "Head Teacher",
  "Security Officer",
  "Sheep Farmer",
  "Silversmith",
  "Social Worker",
  "Soldier",
  "Solicitor",
  "Stockbroker",
  "Stunt Worker",
  "Surgeon",
  "Surveyor",
  "Taxi Driver",
  "Tour Guide",
  "Train Driver",
  "Translator",
  "University Lecturer",
  "Vet",
  "Waiter",
  "Winemaker",
  "Youth Worker",
  "Zoo Keeper"
]
var crimeStory = [
  "True",
  "False",
]
var isCelebrity = [
  "Celebrity",
  "Normal",
]
//THINGS -------------------------------------
var drugList = [
  "Heroin",
  "Acid",
  "LSD",
  "Crack Cocaine",
  "Cocaine",
  "Marajuana",
  "Salvia",
  "Ketamine",
]
var allVehiclesList = [
  "Cable Car",
  "Catamaran",
  "Submarine",
  "Yacht",
  "Sail Boat",
  "Airship",
  "Autogyro",
  "Hot Air Balloon",
  "Blimp",
  "Fixed-wing aircraft",
  "747 Jet",
  "Passenger Jet",
  "Light Aircraft",
  "Glider",
  "Helicopter",
  "Jet Aircraft",
  "Jet Pack",
  "Locomotive",
  "Maglev Train",
  "Monorail",
  "Pedalo",
  "Pogo Stick",
  "Powered Parachute",
  "Tram",
  "Rocket Sled",
  "Zipline",
  "Automobile",
  "Train",
  "Tram",
  "Ambulance",
  "Fire Truck",
  "Range Rover",
  "Police Car",
  "BMW",
  "Audi",
  "All-terrain vehicle",
  "Amphibious vehicle",
  "Auto Rickshaw",
  "Coach",
  "Cycle Rickshaw",
  "Horse",
  "Dog Sled",
  "Tesla",
  "Golf Cart",
  "Hovercraft",
  "Jet Ski",
  "Tank",
  "Troop Carrier",
  "Lamborghini",
  "Ferrari",
  "Minibus",
  "Minivan",
  "Moped",
  "Rickshaw",
  "Race Car",
  "Rover",
  "Bicycle",
  "Bus",
  "Car",
  "Motorcycle",
  "Scooter",
  "Segway",
  "Skateboard",
  "Snowmobile",
  "Space Hopper",
  "Sports Car",
  "SUV",
  "Tractor",
  "Van",
  "Wagon",
  "Wheelbarrow",
  "Wheelchair",
]
var landVehicleList = [
  "Ambulance",
  "Fire Truck",
  "Range Rover",
  "Police Car",
  "BMW",
  "Audi",
  "All-terrain vehicle",
  "Amphibious vehicle",
  "Auto Rickshaw",
  "Coach",
  "Cycle Rickshaw",
  "Horse",
  "Dog Sled",
  "Tesla",
  "Golf Cart",
  "Hovercraft",
  "Jet Ski",
  "Tank",
  "Troop Carrier",
  "Lamborghini",
  "Ferrari",
  "Minibus",
  "Minivan",
  "Moped",
  "Rickshaw",
  "Race Car",
  "Rover",
  "Bicycle",
  "Bus",
  "Car",
  "Motorcycle",
  "Scooter",
  "Segway",
  "Skateboard",
  "Snowmobile",
  "Space Hopper",
  "Sports Car",
  "SUV",
  "Tractor",
  "Van",
  "Wagon",
  "Wheelbarrow",
  "Wheelchair",
]
var smallAnimalList = [
  "Mouse",
  "Rat",
  "Rodent",
  "Squirrel",
  "Beaver",
  "Mole",
  "Rabbit",
  "Fox",
  "Badger",
  "Otter",
  "Weasel",
  "Bat",
  "Seal",
  "Dog",
  "Cat",
  "Ant Eater",
  "Hyena",
  "Monkey",
  "Chimp",
  "Lemur",
  "Hedgehog",
]
var bigAnimalList = [
  "Kangaroo",
  "Ostrich",
  "Walrus",
  "Goat",
  "Sheep",
  "Wild Horse",
  "Horse",
  "Cattle",
  "Dairy Cow",
  "Bull",
  "Leopard",
  "Bear",
  "Grizzly Bear",
  "Polar Bear",
  "Tiger",
  "Cheetah",
  "Lion",
  "Jaguar",
  "Puma",
  "Rhino",
  "Camel",
  "Zebra",
  "Hippo",
  "Giraffe",
  "Elephant",

]
var tenList = [
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
]
var hundList = [
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "48",
  "47",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
  "71",
  "72",
  "73",
  "74",
  "75",
  "76",
  "77",
  "78",
  "79",
  "80",
  "81",
  "82",
  "83",
  "84",
  "85",
  "86",
  "87",
  "88",
  "89",
  "91",
  "90",
  "92",
  "93",
  "94",
  "95",
  "96",
  "97",
  "98",
  "99",
  "100",
]
var newspaperPostfix = [
  "Herald",
  "Times",
  "Express",
  "Informer",
  "Journal",
  "Weekly",
  "Now",
  "Guardian",
  "Post",
  "Chronicle",
  "Gazette",
  "Bulettin",
  "Observer",
  "Enquirer",
  "Dispatch",
  "Star",
  "Standard",
  "News",
  "Corier",
]
var politicalPersonal = [
  "Political",
  "Personal",
]
var companyList = [
  "SpaceX",
  "Tesla",
  "Amazon",
  "Apple",
  "Ebay",
  "Reddit",
  "Microsoft",
  "Walmart",
  "Starbucks",
  "McDonalds",
  "Burger King",
  "KFC",
  "Intel",
  "BMW",
  "Honda",
  "Tencent",
  "Weibo",
  "Costa Coffee",
  "BBC",
  "AirBnB",
  "Uber",
  "Buzzfeed",
  "Reddit",
  "DJI",
  "Etsy",
  "Fitbit",
  "Github",
  "Groupon",
  "Lyft",
  "Spotify",
  "Instagram",
  "Facebook",
  "Tinder",
  "Tumblr",
  "TripAdvisor",
  "Zynga",
  "Volkswagen",
  "BP",
  "Exxon",
  "Amazon",
  "AT&T",
  "Samsung",
  "Toyata",
  "Ford",
  "Foxconn",
  "Total",
  "Best Buy",
  "Canon",
  "Johnson & Johnson",
  "Phizer",
  "British American Tobacco",
  "Bank Of China",
]
// LOCATIONS ----------------------------------
var cityList = [
  "Aberdeen",
  "Adelaide",
  "Algiers",
  "Amsterdam",
  "Ankara",
  "Paraguay",
  "Athens",
  "Auckland",
  "Bangkok",
  "Barcelona",
  "Beijing",
  "Belem",
  "Belfast",
  "Belgrade",
  "Berlin",
  "Birmingham",
  "Bogota",
  "Bombay",
  "Bordeaux",
  "Bremen",
  "Brisbane",
  "Bristol",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Cairo",
  "Calcutta",
  "Canton",
  "Cape Town",
  "Caracas",
  "Cayenne",
  "Chihuahua",
  "Chongqing",
  "Copenhagen",
  "Cordoba",
  "Dakar",
  "Djibouti",
  "Dublin",
  "Durban",
  "Edinburgh",
  "Frankfurt",
  "Georgetown",
  "Glasgow",
  "Guatemala",
  "Hamburg",
  "Havana",
  "Helsinki",
  "Hong Kong",
  "Jakarta",
  "Johannesburg",
  "Kingston",
  "Kuala Lumpur",
  "Leeds",
  "Lisbon",
  "Liverpool",
  "London",
  "Lyons",
  "Madrid",
  "Manchester",
  "Manila",
  "Marseilles",
  "Mecca",
  "Melbourne",
  "Mexico City",
  "Milan",
  "Moscow",
  "Munich",
  "Nagasaki",
  "Nagoya",
  "Nairobi",
  "Nanjing",
  "Naples",
  "New Delhi",
  "Newcastle",
  "Odessa",
  "Osaka",
  "Oslo",
  "Panama City",
  "Paris",
  "Perth",
  "Plymouth",
  "Prague",
  "Reykjavik",
  "Rio de Janeiro",
  "Rome",
  "Salvador",
  "Santiago",
  "St Petersburg",
  "Sao Paulo",
  "Shanghai",
  "Singapore",
  "Stockholm",
  "Sydney",
  "Teheran",
  "Tokyo",
  "Tripoli",
  "Venice",
  "Vienna",
  "Vladivostok",
  "Warsaw",
  "Wellington",
  "Zurich",
];
var countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "North Korea",
  "South Korea",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "St Lucia",
  "Samoa",
  "San Marino",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "U.K",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]
var nationalityList = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusia",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Botswanan",
  "Brazilian",
  "British",
  "Bulgarian",
  "Burmese",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dutch",
  "Ecuadorean",
  "Egyptian",
  "Estonian",
  "Ethiopian",
  "Filipino",
  "Finnish",
  "French",
  "Gambian",
  "German",
  "Ghanaian",
  "Gibraltarian",
  "Greek",
  "Guatemalan",
  "Guyanese",
  "Haitian",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kosovan",
  "Kuwaiti",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Lithuanian",
  "Macanese",
  "Macedonian",
  "Malawian",
  "Malaysian",
  "Maltese",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Namibian",
  "Nepalese",
  "Nigerian",
  "North Korean",
  "Norwegian",
  "Pakistani",
  "Palestinian",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Puerto Rican",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Salvadorean",
  "Samoan",
  "Saudi Arabian",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "St Lucian",
  "Sudanese",
  "Surinamese",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tanzanian",
  "Thai",
  "Tunisian",
  "Turkish",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
];
var criminalOrganisations = [
  "Medellín Cartel",
  "Cali Cartel",
  "Leticia Cartel",
  "Los Nevados Cartel",
  "Los Machos Cartel",
  "Black Eagles",
  "Sinaloa Cartel",
  "Gente Nueva Cartel",
  "Los Ántrax Cartel",
  "Gulf Cartel",
  "Los Rojos Cartel",
  "Los Metros Cartel",
  "Los Zetas Gang",
  "Knights Templar Cartel",
  "La Familia Michoacana",
  "Juárez Cartel",
  "La Linea Cartel",
  "Los Santos Cartel",
  "Guadalajara Cartel",
  "La Barredora Cartel",
  "Los Narcosatánicos Cartel",
  "The American Mafia",
  "Elkins Mob",
  "Leota Mob",
  "Nash Gang",
  "State Line Mob",
  "Negri Organisation",
  "South Florida Faction",
  "DeMeo Mafia",
  "Harlem City Racket",
  "Scicillian Mafia",
  "Irish Mob",
  "Bosnian Mafia",
  "Serbian Mafia",
  "Montenegrin Mafia",
  "Russian Jewish Mafia",
  "Estonian Mafia",
  "Chinese Triads",
  "Japanese Triads",
  "Indian Mafia",
  "Isreali Mafia",
  "Russian Mafia",
  "Turkish Mafia",
  "Klu Klux Klan",
]
var politicalGroups = [
  "Action Party",
  "National Action Party",
  "People's Action Party",
  "Alliance Party",
  "National Alliance",
  "New Alliance Party",
  "Centre Party",
  "Change Party",
  "Christian Party",
  "Christian Democratic Party",
  "Christian Democratic Union",
  "Civic Party",
  "Civic Democratic Party",
  "Communist Party",
  "Communist League",
  "International Communist League",
  "Revolutionary Communist League",
  "Worker-Communist Party",
  "Revolutionary Communist Party",
  "Conservative Party",
  "Democratic Party",
  "Democratic Alliance",
  "Civic Democratic Party",
  "Free Democratic Party",
  "Democratic Labour Party",
  "Liberal Democratic Party",
  "National Democratic Party",
  "National Democratic Congress",
  "New Democratic Party",
  "Democratic People's Party",
  "Progressive Democratic Party",
  "Radical Democratic Party",
  "Social Democratic Party",
  "Social Democratic Union",
  "Democratic Socialist Party",
  "United Democratic Party",
  "Equality Party",
  "Union of Democratic Forces",
  "Free Democratic Party",
  "Freedom Party",
  "Green Party",
  "Independence Party",
  "Labour Party",
  "Socialist Labour Party",
  "Left Party",
  "United Left",
  "Liberal Party",
  "Liberal Democratic Party",
  "National Liberal Party",
  "Radical Liberal Party",
  "Social Liberal Party",
  "Libertarian Party",
  "Motherland Party",
  "National Front",
  "National Alliance",
  "National Democratic Party",
  "National Democratic Congress",
  "National Liberal Party",
  "New National Party",
  "National Socialist Party",
  "National Unity Party",
  "New Alliance Party",
  "New Democratic Party",
  "New National Party",
  "Popular Party",
  "Popular Alliance",
  "National Popular Party",
  "Pirate Party",
  "Progressive Party",
  "Progressive Democratic Party",
  "Radical Party",
  "Radical Democratic Party",
  "Left Radical Party",
  "Reform Party",
  "Liberal Reform Party",
  "National Reform Party",
  "Republican Party",
  "National Republican Party",
  "Revolutionary Party",
  "Revolutionary Communist Party",
  "Social Democratic Party",
  "Social Democratic Union",
  "Socialist Party",
  "Democratic Socialist Party",
  "Socialist Labour Party",
  "National Socialist Party",
  "Socialist Workers Party",
  "Unionist Party",
  "Unity Party",
  "National Unity Party",
  "United Democratic Party",
  "United Workers' Party",
  "Workers' Party",
  "Socialist Workers' Party",
  "United Workers' Party",
  "Worker-Communist Party",
  "Workers' League",
]
// EVENT -----------------------------------
var criminalEventList = [
  "Dumps 7 Newborn Puppies",
  "Is Attacked by [P2]",
  "Arrested For Indecent Exposure with [P2]",
  "Assaults [P2]",
  "Shoots [P2]",
  "Runs Over [P2] With Car",
  "Steals [VEH]",
  "Reportedly Steals [VEH]",
  "Reportedly Hijacks [VEH]",
  "Reportedly Crashes [VEH]",
  "Hijacks [VEH]",
  "Drove [VEH] Under the Influence",
  "Reportedly Drove [VEH] Under the Influence",
  "Reportedly Hijacks [VEH]",
  "Hijacks [VEH]",
  "Drove [VEH] Under the Influence",
  "Reportedly Drove [VEH] Under the Influence",
  "Steals [VEH]",
  "Reportedly Steals [VEH]",
  "Poisons Children",
  "Reportedly Attacks Security",
  "Reportedly Smears Bananas On Cars",
  "Reportedly Steals A Dollar of Snacks",
  "Reportedly Steals Candy",
  "Reportedly Steals Statue",
  "Reportedly Steals Presidential Statue",
  "Reportedly Steals Valuable Artwork",
  "Reportedly Stabs [LOC] Man",
  "Runs Over [P2] With Car",
  "Runs Over Woman with Car",
  "Runs Over Man with Car",
  "Hits Woman with [VEH]",
  "Hits Man with [VEH]",
  "Hits Woman with [VEH]",
  "Hits Man with [VEH]",
  "Crashes Car",
  "Attacks Security",
  "Confesses Obscure Terrorist Plot",
  "Gets Caught Skinny Dipping",
  "Steals Multiple Vehicles",
  "Gets Caught In Drugs Bust",
  "Steals A Dollar of Snacks",
  "Steals Candy",
  "Steals Statue",
  "Steals Presidential Statue",
  "Steals Valuable Artwork",
  "Steals Statue",
  "Stabs [LOC] Man",
  "Releases [BANI] into Crowd",
  "Charged With Child Neglect",
  "Pleasures Themselves In Back Of Cop Car",
  "Bites Head Off of [SMAN]",
  "Pulls Two Guns After 7-Eleven Clerk Refuses Pennies",
  "Bites Dog, Then Brother",
  "Shoots McDonalds Employee,",
  "Shoots Burger King Employee",
  "Robs KFC",
  "Exchanges 12 Shotgun Rounds",
  "Tries To Run Over [P2]",
  "Tries To Run Over Ex-Boyfriend Twice After Break-Up,",
  "Tries To Run Over Ex-Girlfriend Twice After Break-Up,",
  "Shoots [COMP] Employee",
  "Shoots [OCC]",
  "Robs Jewels",
  "Shot During Jewel Heist",
  "Attempts to Steal 9 Million Dollars",
  "Gets Caught Picking Magic Mushrooms",
  "Calls 911 For Ride To Hooters",
  "Advertises Counterfeit Cash For Sale On Craigslist",
  "Stabs [P2] With Sword",
  "Stabs [P2] With Sword",
  "Released Poisonous Snakes,",
  "Hits [P2] with Baseball Bat",
  "Gets into Altercation with [P2]",
  "Charged With Indecent Exposure",
  "Charged With Assault",
  "Charged With Bribery",
  "Charged With Credit Fraud",
  "Charged With Disturbing The Peace",
  "Charged With Securities Fraud",
  "Charged With Public Intoxication",
  "Charged with Public Intoxication",
  "Caught Up In #MeToo Movement",
]
var eventList = [
  "Runs Through Field of Wheat",
  "Runs Through Field of Wheat with [P2]",
  "Crashes [VEH]",
  "Crashes [VEH]",
  "Reportedly Crashes [VEH]",
  "Reportedly Took [DRUG] with [P2]",
  "Throws Drink Over [P2]",
  "Smears Bananas On Cars",
  "Is Caught with [P2]",
  "Reportedly Avoiding Taxes",
  "Confesses To Being Racist",
  "Admits to Being Suicidal",
  "Comes Out as Homosexual",
  "Comes Out as Bisexual",
  "Comes Out as Transgender",
  "Comes Out as Non Binary",
  "Shot Over Argument",
  "Has Mental Breakdown",
  "Gets Wasted",
  "Gets Drunk, Passes Out",
  "Crashes Supercar",
  "Has Baby With Brother",
  "Has Baby With Sister",
  "Adopts A Child",
  "Has Redneck Wedding",
  "Gets Married",
  "Gets Divorced",
  "Calls Fire Department",
  "Donates A Million Dollars To Charity",
  "Took [DRUG]",
  "Says Turtle Army Will Destroy Everyone",
  "Offers Favors For $25 and Chicken McNuggets",
  "Fired For Sleeping With Clients,",
  "Had Daughter Sell Pot Brownies",
  "Reported Drug Deal",
  "Falls Asleep",
  "Calls Cops Because Thermos Containing Semen May Explode,",
  "Shot by Employee",
  "Attacks ATM For ‘Giving Them Too Much Money’",
  "Calls Police to Report A Bomb",
  "Shot Twice After Daring Brother To Shoot Them",
  "Shot Twice After Daring [P2] To Shoot Them",
  "Hits Thief with Bat",
  "Attacked Taking Selfie",
  "Falls Off Building",
  "Falls from Balcony",
  "Has Wardrobe Malfunction",
  "Falls from [VEH]",
  "Is Punched by [P2]",
  "Gets Attacked by Gang",
  "Gets Mugged",
  "Attacked For Wearing Nazi Memorobelia",
  "Claims There is Proof of Aleins",
  "Attacked By [P2]",
  "Reportedly Shot by [P2]",
  "Leaves with [HUND] Women",
  "Claims The Earth is Flat",
  "Claims We Are In A Computer Simulation",
  "Steals [VEH] From [P2]",
  "Thinks [P2] is wrong About [LOC]s",
  "Arrives with [P2]",
];
// PlACE OR MODIFIER ------------------------
var criminalModifierList = [
  "Is Sent To Jail",
  "Appears In Court This Week",
  "At [CITY] Intersection",
  "After Ariving For Jury Duty Drunk,",
  "Will Appear In Court",
  "While Handcuffed",
  "During a Protest",
  "During a Protest in [LOC]",
  "Confesses To Local Police",
  "Escapes in [VEH]",
  "Attempts to Evade Police in [VEH]",
  "Appears for Court Drunk",
  "Appears for Court In [VEH],"
]
var modifiersList = [
  "",
  "In [LOC]",
  "In [CITY]",
  "In [LOC]",
  "In [CITY]",
  "In [LOC]",
  "At [CITY] Nightclub",
  "At [NAT] Nightclub",
  "At Nightclub",
  "at Underage House Party",
  "While At [P2]s Wedding",
  "While On [P2]s Podcast",
  "At [NAT] Art Gallery",
  "Will Appear in [NAT] Court",
  "At [LOC] Art Gallery",
  "At Strip Club",
  "At [CITY] Strip Club",
  "At [NAT] Strip Club",
  "While Making Speech at [P2]s Wedding",
  "At [LOC] Hospital",
  "While Carrying [SMAN] In [LOC]",
  "Wearing Clown Hat In [LOC]",
  "While Wearing Meat",
  "While Wearing Nothing",
  "At [LOC] Fashion Show",
  "At [CITY] Fashion Show",
  "At [NAT] Fashion Show",
  "At [LOC] Film Festival",
  "At [LOC] Airshow",
  "At [LOC] Classic Car Festival",
  "At [LOC] Classic [VEH] Festival",
  "At Classic [VEH] Festival",
  "At [LOC] Music Festival",
  "At [LOC] Business Expo",
  "At [LOC] Airport",
  "At [LOC] Mall",
  "In Downtown [LOC]",
  "At [LOC] Restaraunt",
  "After Show in [LOC]",
  "In [LOC]",
  "While Begging For Money In [LOC]",
  "Playing Show in [LOC]",
  "While Making a Speech In [LOC]",
  "After Making a Speech In [LOC]",
  "At a Speech in [LOC]",
  "At Climate Demonstration",
  "Nobody Injured",
  "On [LOC] Beach",
  "On Mountain In [LOC]",
];
