$(document).ready(function() {


  // PEOPLE ---------------------------------
  var peopleList = [
    "Adam Sandler",
    "Adele",
    "Ariana Grande",
    "Al Pacino",
    "Angelina Jolie",
    "Anthony Hopkins",
    "Arnold Schwarzenegger",
    "Ashton Kutcher",
    "Barbara Streisand",
    "Ben Affleck",
    "Ben Stiller",
    "Benedict Cumberbatch",
    "Beyonce",
    "Bill Murray",
    "Bill O'Reilly",
    "Bill Paxton",
    "Billy Joel",
    "Bon Jovi",
    "Brad Pitt",
    "Brian Cox",
    "Elon Musk",
    "Joe Rogan",
    "Ozzy Osbourne",
    "Britney Spears",
    "Bruce Lee",
    "Bruce Springsteen",
    "Bruce Willis",
    "Bruno Mars",
    "Calvin Harris",
    "Cameron Diaz",
    "Carrie Fisher",
    "Catherine Zeta-Jones",
    "Celine Dion",
    "Chance The Rapper",
    "Channing Tatum",
    "Charlie Sheen",
    "Cher",
    "Chris Evans",
    "Chris Hemsworth",
    "Chris Martin",
    "Chris Rock",
    "Chris Tucker",
    "Christian Bale",
    "Christopher Reeve",
    "Christopher Walken",
    "Chuck Norris",
    "Clint Eastwood",
    "Colin Farrell",
    "Colin Firth",
    "Conor McGregor",
    "Courteney Cox",
    "Cristiano Ronaldo",
    "Dakota Fanning",
    "Daniel Craig",
    "Daniel Radcliffe",
    "Danny DeVito",
    "Danny Glover",
    "Dave Chappelle",
    "Demi Moore",
    "Dennis Hopper",
    "Denzel Washington",
    "Dick Van Dyke",
    "Dolly Parton",
    "Dr. Dre",
    "Dr. Phil",
    "Drake",
    "Drew Barrymore",
    "Dustin Hoffman",
    "Dwayne Johnson",
    "Ed Sheeran",
    "Eddie Murphy",
    "Ellen DeGeneres",
    "Ellen Page",
    "Elton John",
    "Emilia Clarke",
    "Emma Watson",
    "Eva Mendes",
    "Fernando Alonso",
    "Forest Whitaker",
    "Gareth Bale",
    "Gene Wilder",
    "George Clooney",
    "Gordon Ramsay",
    "Grace Kelly",
    "Guy Pearce",
    "Gwyneth Paltrow",
    "Halle Berry",
    "Harrison Ford",
    "Heath Ledger",
    "Helen Mirren",
    "Helena Bonham Carter",
    "Hilary Duff",
    "Hilary Swank",
    "Howard Stern",
    "Hugh Grant",
    "Hugh Jackman",
    "Hugh Laurie",
    "Ian McKellen",
    "Ice Cube",
    "Idris Elba",
    "J.K Rowling",
    "Jack Nicholson",
    "Jackie Chan",
    "Jake Gyllenhaal",
    "James Franco",
    "James Woods",
    "Jamie Foxx",
    "Jared Leto",
    "Jason Statham",
    "Jay Z",
    "Jennifer Aniston",
    "Jennifer Hudson",
    "Jennifer Lawrence",
    "Jennifer Lopez",
    "Jessica Alba",
    "Jet Li",
    "Jim Carrey",
    "Joaquin Phoenix",
    "Joe Pesci",
    "John Travolta",
    "Johnny Depp",
    "Johnny Knoxville",
    "Jude Law",
    "Judi Dench",
    "Julia Roberts",
    "Justin Bieber",
    "Justin Timberlake",
    "Kate Beckinsale",
    "Kate Hudson",
    "Kate Winslet",
    "Katy Perry",
    "Keanu Reeves",
    "Keira Knightley",
    "Kevin Bacon",
    "Kevin Costner",
    "Kevin Hart",
    "Kevin Spacey",
    "Kim Basinger",
    "Kim Kardashian",
    "Laurence Fishbourne",
    "LeBron James",
    "Leonardo DiCaprio",
    "Lewis Hamilton",
    "Liam Neeson",
    "Lindsay Lohan",
    "Lionel Messi",
    "Lisa Kudrow",
    "Louis C.K.",
    "Ludacris",
    "Macaulay Culkin",
    "Mark Hamill",
    "Mark Wahlberg",
    "Marlon Brando",
    "Marlon Wayans",
    "Matthew McConaughey",
    "Meg Ryan",
    "Megan Fox",
    "Mel Gibson",
    "Meryl Streep",
    "Michael J. Fox",
    "Mike Myers",
    "Mila Kunis",
    "Miley Cyrus",
    "Morgan Freeman",
    "Natalie Portman",
    "Neymar",
    "Nia Long",
    "Nick Frost",
    "Nicole Kidman",
    "Novak Djokovic",
    "Orlando Bloom",
    "Patrick Swayze",
    "Penelope Cruz",
    "Pierce Brosnan",
    "Queen Latifah",
    "Reese Witherspoon",
    "Renee Zellweger",
    "Rihanna",
    "Rob Schneider",
    "Robert De Niro",
    "Robert Downey Jr.",
    "Russell Brand",
    "Russell Crowe",
    "Ryan Gosling",
    "Ryan Reynolds",
    "Sacha Baron Cohen",
    "Samuel L. Jackson",
    "Sandra Bullock",
    "Scarlett Johansson",
    "Sean Bean",
    "Sean Connery",
    "Sean Diddy Combs",
    "Sebastian Vettel",
    "Selena Gomez",
    "Seth Green",
    "Seth MacFarlane",
    "Shia LaBeouf",
    "Simon Cowell",
    "Simon Pegg",
    "Stephen Curry",
    "Steve Buscemi",
    "Sylvester Stallone",
    "Taylor Swift",
    "Tiger Woods",
    "Tom Cruise",
    "Tom Hanks",
    "Usain Bolt",
    "Vin Diesel",
    "Whitney Houston",
    "Whoopi Goldberg",
    "Will Ferrell",
    "Donald Trump",
    "Theresa May",
    "Will Smith",
    "Zac Efron",
    "Oprah Winfrey",
    "Kendall Jenner",
    "Cara Delevingne",
    "Kate Moss",
    "Pixie Lott",
    "R. Kelly",
    "Tito Ortiz",
    "Demi Lovato",
    "Jimmy Kimmel",
    "Jay Leno",
    "Macy Gray",
    "Khloé Kardashian",
    "J. Cole",
    "Sam Smith",
    "Soulja Boy",
    "Terry Crews",
    "Man",
    "Woman",
    "Drunk Man",
    "Drunk Woman",
    "Man",
    "Woman",
    "Drunk Man",
    "Drunk Woman",
    "Man",
    "Woman",
    "Drunk Man",
    "Drunk Woman",
    "Man",
    "Woman",
    "Drunk Man",
    "Drunk Woman",
    "Couple",
    "High School Student",
    "Homeless Man",
    "Homeless Woman",
    "Man",
    "Woman",
    "Drunk Man",
    "Doctor",
    "Nurse",
    "Drunk Doctor",
    "Drunk Nurse",
    "LOC Doctor",
    "LOC Nurse",
    "Drunk LOC Doctor",
    "Drunk LOC Nurse",
    "Surgeon",
    "Drunk Surgeon",
    "Drunk LOC Surgeon",
    "Drunk Woman",
    "Couple",
    "High School Student",
    "Homeless Man",
    "Homeless Woman",
    "Firefighter",
    "Paramedic",
    "Sherriff ",
    "Police Officer",
    "Garbage Man",
    "Bomb Disposal Worker",
    "Lifeguard",
    "LOC Man",
    "LOC Woman",
    "LOC Man",
    "LOC Woman",
    "LOC Man",
    "LOC Woman",
    "LOC Man",
    "LOC Woman",
    "Drunk LOC Man",
    "Drunk LOC Woman",
    "LOC Couple",
    "LOC High School Student",
    "LOC Homeless Man",
    "LOC Homeless Woman",
    "LOC Firefighter",
    "LOC Paramedic",
    "LOC Sheriff",
    "LOC Police Officer",
    "LOC Garbage Man",
    "LOC Bomb Disposal Worker",
    "LOC Lifeguard",
    "Man",
    "Woman",
    "Drunk Man",
    "Drunk Woman",
    "Man",
    "Woman",
    "Drunk Man",
    "Drunk Woman",
    "Man",
    "Woman",
    "Drunk Man",
    "Drunk Woman",
    "Couple",
    "High School Student",
    "Homeless Man",
    "Homeless Woman",
    "Man",
    "Woman",
    "Drunk Man",
    "Doctor",
    "Nurse",
    "Drunk Doctor",
    "Drunk Nurse",
    "LOC Doctor",
    "LOC Nurse",
    "Drunk LOC Doctor",
    "Drunk LOC Nurse",
    "Surgeon",
    "Drunk Surgeon",
    "Drunk LOC Surgeon",
    "Drunk Woman",
    "Couple",
    "High School Student",
    "Homeless Man",
    "Homeless Woman",
    "Firefighter",
    "Paramedic",
    "Sherriff ",
    "Police Officer",
    "Garbage Man",
    "Bomb Disposal Worker",
    "Lifeguard",
    "LOC Man",
    "LOC University Student",
    "University Student",
    "LOC Woman",
    "Drunk LOC Man",
    "Drunk LOC Woman",
    "LOC Couple",
    "LOC High School Student",
    "LOC Homeless Man",
    "LOC Homeless Woman",
    "LOC Firefighter",
    "LOC Paramedic",
    "LOC Sheriff",
    "LOC Police Officer",
    "LOC Garbage Man",
    "LOC Bomb Disposal Worker",
    "LOC Lifeguard",
  ];

  // EVENT --------------------------------------------------
  var eventList = [
    "Is Attacked by P2",
    "Arrested For Indecent Exposure with P2",
    "Assaults P2",
    "Shoots P2",
    "Runs Over P2 With Car",
    "Crashes VEH",
    "Reportedly Crashes VEH",
    "Steals VEH",
    "Reportedly Steals VEH",
    "Reportedly Hijacks VEH",
    "Hijacks VEH",
    "Drove VEH Under the Influence",
    "Reportedly Drove VEH Under the Influence",
    "Crashes VEH",
    "Reportedly Crashes VEH",
    "Steals VEH",
    "Reportedly Steals VEH",
    "Reportedly Hijacks VEH",
    "Hijacks VEH",
    "Drove VEH Under the Influence",
    "Reportedly Drove VEH Under the Influence",
    "Reportedly Took LSD with P2",
    "Reportedly Smoked Marajuana with P2",
    "Reportedly Smoked Salvia with P2",
    "Reportedly Attacks Security",
    "Reportedly Smears Bananas On Cars",
    "Poisons Children",
    "Throws Drink Over P2",
    "Reportedly Steals A Dollar of Snacks",
    "Reportedly Steals Candy",
    "Reportedly Steals Statue",
    "Reportedly Steals Presidential Statue",
    "Reportedly Steals Valuable Artwork",
    "Reportedly Stabs LOC Man",
    "Runs Over P2 With Car",
    "Runs Over Woman with Car",
    "Runs Over Man with Car",
    "Hits Woman with VEH",
    "Hits Man with VEH",
    "Hits Woman with VEH",
    "Hits Man with VEH",
    "Crashes Car",
    "Attacks Security",
    "Smears Bananas On Cars",
    "Steals Multiple Vehicles",
    "Gets Arrested Skinny Dipping",
    "Is Caught with P2",
    "Gets Caught In Drugs Bust",
    "Reportedly Avoiding Taxes",
    "Confesses Obscure Terrorist Plot",
    "Confesses To Being Racist",
    "Admits to Being Suicidal",
    "Comes Out as Homosexual",
    "Comes Out as Bisexual",
    "Comes Out as Transgender",
    "Comes Out as Non Binary",
    "Steals A Dollar of Snacks",
    "Steals Candy",
    "Steals Statue",
    "Steals Presidential Statue",
    "Steals Valuable Artwork",
    "Steals Statue",
    "Stabs LOC Man",
    "Exchanges 12 Shotgun Rounds",
    "Arrested For Throwing Alligator",
    "Charged With Child Neglect",
    "Shot Over Argument",
    "Has Mental Breakdown",
    "Gets Wasted",
    "Gets Drunk, Passes Out",
    "Pulls Bull Shark From Ocean",
    "Pleasures Themselves In Back Of Cop Car",
    "Crashes Supercar",
    "Has Baby With Brother",
    "Has Baby With Sister",
    "Adopts A Child",
    "Jailed",
    "Pulls Two Guns After 7-Eleven Clerk Refuses Pennies",
    "Charged After Biting Off Chicken’s Head",
    "Has Redneck Wedding",
    "Gets Married",
    "Gets Divorced",
    "Calls Fire Department",
    "Smoked Crack",
    "Donates A Million Dollars To Charity",
    "Smoked Marajuana",
    "Says Turtle Army Will Destroy Everyone",
    "Had Daughter Sell Pot Brownies",
    "Bites Dog, Then Brother",
    "Shoots McDonalds Employee,",
    "Shoots Burger King Employee",
    "Robs KFC",
    "Offers Favors For $25 and Chicken McNuggets",
    "Fired For Sleeping With Clients,",
    "Tries To Run Over P2",
    "Tries To Run Over Ex-Boyfriend Twice After Break-Up,",
    "Tries To Run Over Ex-Girlfriend Twice After Break-Up,",
    "Reported Drug Deal Robbery,",
    "Falls Asleep",
    "Calls Cops Because Thermos Containing Semen May Explode,",
    "Shot by Casino Employee",
    "Shoots Casino Employee",
    "Shoots Blackjack Dealer",
    "Robs Jewels",
    "Shot During Jewel Heist",
    "Attempts to Steal 9 Million Dollars",
    "Charged With Picking Magic Mushrooms",
    "Calls 911 For Ride To Hooters",
    "Advertises Counterfeit Cash For Sale On Craigslist",
    "Stabs P2 With Sword",
    "Stabs P2 With Sword",
    "Attacks ATM For ‘Giving Them Too Much Money’",
    "Calls Police to Report A Bomb",
    "Released Poisonous Snakes,",
    "Shot Twice After Daring Brother To Shoot Them",
    "Shot Twice After Daring P2 To Shoot Them",
    "Hits Burglar with Bat",
    "Hits P2 with Baseball Bat",
    "Attacked Taking Selfie",
    "Falls Off Building",
    "Falls from Balcony",
    "Has Wardrobe Malfunction",
    "Falls from VEH",
    "Gets into Altercation with P2",
    "Is Punched by P2",
    "Gets Attacked by Gang",
    "Gets Mugged",
    "Arrested For Indecent Exposure",
    "Arrested For Assault",
    "Arrested For Bribery",
    "Arrested For Credit Fraud",
    "Arrested For Disturbing The Peace",
    "Arrested For Securities Fraud",
    "Arrested for Public Intoxication",
    "Charged with Public Intoxication",
    "Caught Up In #MeToo Movement",
    "Attacked For Wearing Nazi Memorobelia",
    "Claims There is Proof of Aleins",
    "Attacked By P2",
    "Reportedly Shot by P2",
    "Leaves with 30 Women",
    "Leaves with 30 Women",
    "Claims The Earth is Flat",
    "Claims We Are In A Computer Simulation",
    "Steals VEH From P2",
    "Thinks P2 is wrong About LOC",
    "Arrives with P2",
  ];

  // PlACE OR MODIFIER ----------------------------------
  var modifiersList = [
    "",
    "In LOC",
    "In LOC",
    "In LOC",
    "In LOC",
    "In LOC",
    "At LOC Nightclub",
    "At Nightclub",
    "at Underage House Party",
    "While At P2s Wedding",
    "While On P2s Podcast",
    "Is Sent To Jail",
    "Appears In Court This Week",
    "At LOC Intersection",
    "At LOC Art Gallery",
    "Will Appear In Court",
    "At Strip Club",
    "After Ariving For Jury Duty Drunk,",
    "While Making Speech at P2s Wedding",
    "At LOC Hospital",
    "While Carrying An Alligator In LOC",
    "Wearing Clown Hat In LOC",
    "While Wearing Meat",
    "While Handcuffed",
    "While Wearing Nothing",
    "At LOC Fashion Show",
    "At LOC Film Festival",
    "At LOC Airshow",
    "At LOC Classic Car Festival",
    "At LOC Classic VEH Festival",
    "At Classic VEH Festival",
    "At LOC Music Festival",
    "At LOC Business Expo",
    "At LOC Airport",
    "At LOC Mall",
    "In Downtown LOC",
    "At LOC Restaraunt",
    "After Show in LOC",
    "In LOC",
    "While Begging For Money In LOC",
    "Playing Show in LOC",
    "While Making a Speech In LOC",
    "After Making a Speech In LOC",
    "During a Protest",
    "During a Protest in LOC",
    "At a Speech in LOC",
    "At Climate Demonstration",
    "Nobody Injured",
    "On LOC Beach",
    "On Mountain In LOC",
    "Confesses To Local Police",
    "Escapes in VEH",
    "Attempts to Evade Police in VEH",
    "Appears for Court Drunk",
    "Appears for Court In VEH,"
  ];

  // LOCATIONS -------------------------------------------------
  var locationsList = [
    "Aberdeen",
    "Adelaide",
    "Algiers",
    "Amsterdam",
    "Ankara",
    "Paraguay",
    "Athens",
    "Auckland",
    "Bangkok",
    "Barcelona",
    "Beijing",
    "Belem",
    "Belfast",
    "Belgrade",
    "Berlin",
    "Birmingham",
    "Bogota",
    "Bombay",
    "Bordeaux",
    "Bremen",
    "Brisbane",
    "Bristol",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Cairo",
    "Calcutta",
    "Canton",
    "Cape Town",
    "Caracas",
    "Cayenne",
    "Chihuahua",
    "Chongqing",
    "Copenhagen",
    "Cordoba",
    "Dakar",
    "Darwin",
    "Djibouti",
    "Dublin",
    "Durban",
    "Edinburgh",
    "Frankfurt",
    "Georgetown",
    "Glasgow",
    "Guatemala",
    "Hamburg",
    "Havana",
    "Helsinki",
    "Hong Kong",
    "Jakarta",
    "Johannesburg",
    "Kingston",
    "Kuala Lumpur",
    "Leeds",
    "Lisbon",
    "Liverpool",
    "London",
    "Lyons",
    "Madrid",
    "Manchester",
    "Manila",
    "Marseilles",
    "Mecca",
    "Melbourne",
    "Mexico City",
    "Milan",
    "Moscow",
    "Munich",
    "Nagasaki",
    "Nagoya",
    "Nairobi",
    "Nanjing",
    "Naples",
    "New Delhi",
    "Newcastle",
    "Odessa",
    "Osaka",
    "Oslo",
    "Panama City",
    "Paris",
    "Perth",
    "Plymouth",
    "Prague",
    "Reykjavik",
    "Rio de Janeiro",
    "Rome",
    "Salvador",
    "Santiago",
    "St Petersburg",
    "Sao Paulo",
    "Shanghai",
    "Singapore",
    "Stockholm",
    "Sydney",
    "Teheran",
    "Tokyo",
    "Tripoli",
    "Venice",
    "Vienna",
    "Vladivostok",
    "Warsaw",
    "Wellington",
    "Zurich",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "South Korea",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "St Lucia",
    "Samoa",
    "San Marino",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "U.K",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];

  var vehicleList = [
    "Ambulance",
    "Fire Truck",
    "Range Rover",
    "Police Car",
    "BMW",
    "Audi",
    "All-terrain vehicle",
    "Amphibious vehicle",
    "Amphibious vehicle",
    "Auto Rickshaw",
    "Cable Car",
    "Catamaran",
    "Coach",
    "Cycle Rickshaw",
    "Horse",
    "Submarine",
    "Diving Bell",
    "Dog Sled",
    "Tesla",
    "Golf Cart",
    "Hovercraft",
    "Jet Ski",
    "Yacht",
    "Tank",
    "Troop Carrier",
    "Lamborghini",
    "Ferrari",
    "Sail Boat",
    "Airship",
    "Autogyro",
    "Hot Air Balloon",
    "Blimp",
    "Fixed-wing aircraft",
    "Glider",
    "Helicopter",
    "Jet Aircraft",
    "Jet Pack",
    "Locomotive",
    "Maglev",
    "Minibus",
    "Minivan",
    "Monorail",
    "Monowheel",
    "Moped",
    "Ornithopter",
    "Rickshaw",
    "Pedalo",
    "Pogo Stick",
    "Powered Parachute",
    "Quadracycle",
    "Race Car",
    "Road Train",
    "Rocket",
    "Rocket Sled",
    "Rover",
    "Zipline",
    "Automobile",
    "Bicycle",
    "Bus",
    "Car",
    "Motorcycle",
    "Scooter",
    "Segway",
    "Skateboard",
    "Snowmobile",
    "Space Hopper",
    "Sports Car",
    "SUV",
    "Tractor",
    "Train",
    "Tram",
    "Tricycle",
    "Van",
    "Wagon",
    "Wheelbarrow",
    "Wheelchair",
  ];

  $('.btn').click(function() {
    // fade out items on click
    $('#first').fadeOut(1);
    $('#second').fadeOut(1);
    $('#third').fadeOut(1);

    // set up vars for Person/Event/Modifier
    var first = $('#first'); // Person
    var second = $('#second'); // Event
    var third = $('#third'); // Modifier


    //Generate Random Numbers for Items
    var randomPerson = peopleList[Math.floor(Math.random() * peopleList.length)];
    var randomEvent = eventList[Math.floor(Math.random() * eventList.length)];
    var randomModifier = modifiersList[Math.floor(Math.random() * modifiersList.length)];
    var randomLocation = locationsList[Math.floor(Math.random() * locationsList.length)];
    var randomLocation2 = locationsList[Math.floor(Math.random() * locationsList.length)];
    var randomLocation3 = locationsList[Math.floor(Math.random() * locationsList.length)];
    var randomPerson2 = peopleList[Math.floor(Math.random() * peopleList.length)];
    var randomPerson3 = peopleList[Math.floor(Math.random() * peopleList.length)];
    var randomVehicle = vehicleList[Math.floor(Math.random() * vehicleList.length)];
    var randomVehicle2 = vehicleList[Math.floor(Math.random() * vehicleList.length)];

    // LOG OUTPUTS
    console.log(
      randomPerson,
      randomEvent,
      randomModifier,
      randomLocation,
      randomLocation2,
      randomLocation3,
      randomPerson2,
      randomPerson3,
      randomVehicle,

    );
    first.delay(50).html(randomPerson.replace("LOC", randomLocation).replace("Veh", randomVehicle));
    second.delay(50).html(randomEvent.replace("P2", randomPerson2).replace('LOC', randomLocation2).replace("VEH", randomVehicle));
    third.delay(50).html(randomModifier.replace("P2", randomPerson3).replace('LOC', randomLocation3).replace("VEH", randomVehicle2));
    $('#first').fadeIn(100);
    $('#second').delay(600).fadeIn(100);
    $('#third').delay(1200).fadeIn(100);
  });
});
